
version: 2
jobs:
  build:
    docker:
      - image: codehz/mcpe-sdk:mod
    working_directory: /data/projects
    steps:
      - checkout
      - run: CPP=/data/sdk/bin/i686-linux-android-g++ make -j $(nproc)

      - store_artifacts:
          path: /data/projects/out

workflows:
  version: 2
  build:
    jobs:
      - build