
version: 2
jobs:
  build:
    docker:
      - image: codehz/mcpe-sdk:mod
    working_directory: /data/projects
    steps:
      - checkout
      - run:
          name: build
          command: make
          environment:
            CPP: /data/sdk/bin/i686-linux-android-g++
            CC : /data/sdk/bin/i686-linux-android-gcc
      - run:
          name: package
          command:
            cd /data/projects/out
            tar cvf mods.tar.xz *.so
      - store_artifacts:
          path: /data/projects/out/mods.tar.xz

workflows:
  version: 2
  build:
    jobs:
      - build